from heppy.framework.analyzer import Analyzer
from heppy.statistics.tree import Tree
from heppy.analyzers.ntuple import *
from heppy.particles.tlv.resonance import Resonance2 as Resonance
from heppy.utils.deltar import matchObjectCollection, deltaR

from ROOT import TFile, TLorentzVector
import ROOT
import array


kl_list=['000','040','070','100','130','150','170','200','220','240','260','300']


class TreeProducer(Analyzer):

    def beginLoop(self, setup):
        super(TreeProducer, self).beginLoop(setup)
        self.rootfile = TFile('/'.join([self.dirName,
                                        'tree.root']),
                              'recreate')
        self.tree = Tree( 'events', '')
        self.tree.var('weight', float)

        self.tree.var('nljets', float)
        self.tree.var('nbjets', float)
        self.tree.var('njets', float)
        self.tree.var('nlep', float)
        self.tree.var('drbb', float)
        self.tree.var('draa', float)

        bookParticle(self.tree, 'haa')
        bookParticle(self.tree, 'hbb')
        bookLepton(self.tree, 'a1')
        bookLepton(self.tree, 'a2')
        bookLepton(self.tree, 'b1')
        bookLepton(self.tree, 'b2')        
        bookParticle(self.tree, 'hh')

        bookMet(self.tree, 'met') 

        self.bdt_a1_pt      = dict()
        self.bdt_a1_pt      = dict()  
        self.bdt_a1_eta     = dict()
        self.bdt_a1_phi     = dict() 
        self.bdt_a2_pt      = dict() 
        self.bdt_a2_eta     = dict() 
        self.bdt_a2_phi     = dict()
        self.bdt_b1_pt      = dict() 
        self.bdt_b1_eta     = dict() 
        self.bdt_b1_phi     = dict() 
        self.bdt_b2_pt      = dict() 
        self.bdt_b2_eta     = dict()
        self.bdt_b2_phi     = dict()
        self.bdt_met_pt     = dict() 
        self.bdt_met_phi    = dict()
        self.bdt_met_px     = dict()
        self.bdt_met_py     = dict() 
        self.bdt_haa_pt     = dict() 
        self.bdt_haa_eta    = dict()
        self.bdt_haa_phi    = dict()
        self.bdt_haa_m      = dict() 
        self.bdt_hbb_pt     = dict()
        self.bdt_hbb_eta    = dict()
        self.bdt_hbb_phi    = dict()
        self.bdt_hbb_m      = dict()
        self.bdt_hh_pt      = dict()
        self.bdt_hh_eta     = dict()
        self.bdt_hh_phi     = dict()
        self.bdt_hh_m       = dict()
        self.bdt_njets      = dict()
        self.bdt_nbjets     = dict()
        self.bdt_nljets     = dict()
        
        self.bdt2_a1_pt     = dict()
        self.bdt2_a1_eta    = dict()
        self.bdt2_a1_phi    = dict()
        self.bdt2_a2_pt     = dict()
        self.bdt2_a2_eta    = dict()
        self.bdt2_a2_phi    = dict()
        self.bdt2_b1_pt     = dict()
        self.bdt2_b1_eta    = dict()
        self.bdt2_b1_phi    = dict()
        self.bdt2_b2_pt     = dict()
        self.bdt2_b2_eta    = dict()
        self.bdt2_b2_phi    = dict()
        self.bdt2_met_pt    = dict()
        self.bdt2_met_phi   = dict()
        self.bdt2_met_px    = dict()
        self.bdt2_met_py    = dict()
        self.bdt2_haa_pt    = dict()
        self.bdt2_haa_eta   = dict()
        self.bdt2_haa_phi   = dict()
        self.bdt2_haa_m     = dict()
        self.bdt2_hbb_pt    = dict()
        self.bdt2_hbb_eta   = dict()
        self.bdt2_hbb_phi   = dict()
        self.bdt2_hbb_m     = dict()
        self.bdt2_hh_pt     = dict()
        self.bdt2_hh_eta    = dict()
        self.bdt2_hh_phi    = dict()
        self.bdt2_hh_m      = dict()
        self.bdt2_njets     = dict()
        self.bdt2_nbjets    = dict()
        self.bdt2_nljets    = dict()
        self.reader         = dict()
        self.reader2        = dict()
        
        for kl in kl_list:
            self.bdt_a1_pt['bdt_a1_pt_{}'.format(kl)]        = array.array( 'f', [ 0. ] )
            self.bdt_a1_eta['bdt_a1_eta_{}'.format(kl)]      = array.array( 'f', [ 0. ] )  
            self.bdt_a1_phi['bdt_a1_phi_{}'.format(kl)]      = array.array( 'f', [ 0. ] )   
            self.bdt_a2_pt['bdt_a2_pt_{}'.format(kl)]        = array.array( 'f', [ 0. ] )   
            self.bdt_a2_eta['bdt_a2_eta_{}'.format(kl)]      = array.array( 'f', [ 0. ] )   
            self.bdt_a2_phi['bdt_a2_phi_{}'.format(kl)]      = array.array( 'f', [ 0. ] )   
            self.bdt_b1_pt['bdt_b1_pt_{}'.format(kl)]        = array.array( 'f', [ 0. ] )   
            self.bdt_b1_eta['bdt_b1_eta_{}'.format(kl)]      = array.array( 'f', [ 0. ] )   
            self.bdt_b1_phi['bdt_b1_phi_{}'.format(kl)]      = array.array( 'f', [ 0. ] )   
            self.bdt_b2_pt['bdt_b2_pt_{}'.format(kl)]        = array.array( 'f', [ 0. ] )   
            self.bdt_b2_eta['bdt_b2_eta_{}'.format(kl)]      = array.array( 'f', [ 0. ] )   
            self.bdt_b2_phi['bdt_b2_phi_{}'.format(kl)]      = array.array( 'f', [ 0. ] )   
            self.bdt_met_pt['bdt_met_pt_{}'.format(kl)]      = array.array( 'f', [ 0. ] )   
            self.bdt_met_phi['bdt_met_phi_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt_met_px['bdt_met_px_{}'.format(kl)]      = array.array( 'f', [ 0. ] )   
            self.bdt_met_py['bdt_met_py_{}'.format(kl)]      = array.array( 'f', [ 0. ] )   
            self.bdt_haa_pt['bdt_haa_pt_{}'.format(kl)]      = array.array( 'f', [ 0. ] )   
            self.bdt_haa_eta['bdt_haa_eta_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt_haa_phi['bdt_haa_phi_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt_haa_m['bdt_haa_m_{}'.format(kl)]        = array.array( 'f', [ 0. ] )  
            self.bdt_hbb_pt['bdt_hbb_pt_{}'.format(kl)]      = array.array( 'f', [ 0. ] )  
            self.bdt_hbb_eta['bdt_hbb_eta_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt_hbb_phi['bdt_hbb_phi_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt_hbb_m['bdt_hbb_m_{}'.format(kl)]        = array.array( 'f', [ 0. ] )  
            self.bdt_hh_pt['bdt_hh_pt_{}'.format(kl)]        = array.array( 'f', [ 0. ] )  
            self.bdt_hh_eta['bdt_hh_eta_{}'.format(kl)]      = array.array( 'f', [ 0. ] )  
            self.bdt_hh_phi['bdt_hh_phi_{}'.format(kl)]      = array.array( 'f', [ 0. ] )  
            self.bdt_hh_m['bdt_hh_m_{}'.format(kl)]          = array.array( 'f', [ 0. ] )  
            self.bdt_njets['bdt_njets_{}'.format(kl)]        = array.array( 'f', [ 0. ] )  
            self.bdt_nbjets['bdt_nbjets_{}'.format(kl)]      = array.array( 'f', [ 0. ] )  
            self.bdt_nljets['bdt_nljets_{}'.format(kl)]      = array.array( 'f', [ 0. ] )  
                                       
            self.bdt2_a1_pt  ['bdt2_a1_pt_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt2_a1_eta ['bdt2_a1_eta_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_a1_phi ['bdt2_a1_phi_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_a2_pt  ['bdt2_a2_pt_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt2_a2_eta ['bdt2_a2_eta_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_a2_phi ['bdt2_a2_phi_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_b1_pt  ['bdt2_b1_pt_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt2_b1_eta ['bdt2_b1_eta_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_b1_phi ['bdt2_b1_phi_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_b2_pt  ['bdt2_b2_pt_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt2_b2_eta ['bdt2_b2_eta_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_b2_phi ['bdt2_b2_phi_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_met_pt ['bdt2_met_pt_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_met_phi['bdt2_met_phi_{}'.format(kl)]  = array.array( 'f', [ 0. ] )  
            self.bdt2_met_px ['bdt2_met_px_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_met_py ['bdt2_met_py_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_haa_pt ['bdt2_haa_pt_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_haa_eta['bdt2_haa_eta_{}'.format(kl)]  = array.array( 'f', [ 0. ] )  
            self.bdt2_haa_phi['bdt2_haa_phi_{}'.format(kl)]  = array.array( 'f', [ 0. ] )  
            self.bdt2_haa_m  ['bdt2_haa_m_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt2_hbb_pt ['bdt2_hbb_pt_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_hbb_eta['bdt2_hbb_eta_{}'.format(kl)]  = array.array( 'f', [ 0. ] )  
            self.bdt2_hbb_phi['bdt2_hbb_phi_{}'.format(kl)]  = array.array( 'f', [ 0. ] )  
            self.bdt2_hbb_m  ['bdt2_hbb_m_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt2_hh_pt  ['bdt2_hh_pt_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt2_hh_eta ['bdt2_hh_eta_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_hh_phi ['bdt2_hh_phi_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_hh_m   ['bdt2_hh_m_{}'.format(kl)]     = array.array( 'f', [ 0. ] )  
            self.bdt2_njets  ['bdt2_njets_{}'.format(kl)]    = array.array( 'f', [ 0. ] )  
            self.bdt2_nbjets ['bdt2_nbjets_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  
            self.bdt2_nljets ['bdt2_nljets_{}'.format(kl)]   = array.array( 'f', [ 0. ] )  

            self.reader['reader_{}'.format(kl)]   = ROOT.TMVA.Reader()
            self.reader2['reader2_{}'.format(kl)] = ROOT.TMVA.Reader()

            self.reader['reader_{}'.format(kl)].AddVariable('a1_pt'	  ,  self.bdt_a1_pt   ['bdt_a1_pt_{}'.format(kl)]     )
            self.reader['reader_{}'.format(kl)].AddVariable('a1_eta'	  ,  self.bdt_a1_eta  ['bdt_a1_eta_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('a1_phi'	  ,  self.bdt_a1_phi  ['bdt_a1_phi_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('a2_pt'	  ,  self.bdt_a2_pt   ['bdt_a2_pt_{}'.format(kl)]     )
            self.reader['reader_{}'.format(kl)].AddVariable('a2_eta'	  ,  self.bdt_a2_eta  ['bdt_a2_eta_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('a2_phi'	  ,  self.bdt_a2_phi  ['bdt_a2_phi_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('b1_pt'	  ,  self.bdt_b1_pt   ['bdt_b1_pt_{}'.format(kl)]     )
            self.reader['reader_{}'.format(kl)].AddVariable('b1_eta'	  ,  self.bdt_b1_eta  ['bdt_b1_eta_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('b1_phi'	  ,  self.bdt_b1_phi  ['bdt_b1_phi_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('b2_pt'	  ,  self.bdt_b2_pt   ['bdt_b2_pt_{}'.format(kl)]     )
            self.reader['reader_{}'.format(kl)].AddVariable('b2_eta'	  ,  self.bdt_b2_eta  ['bdt_b2_eta_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('b2_phi'	  ,  self.bdt_b2_phi  ['bdt_b2_phi_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('met_pt'	  ,  self.bdt_met_pt  ['bdt_met_pt_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('met_phi'	  ,  self.bdt_met_phi ['bdt_met_phi_{}'.format(kl)]   )
            self.reader['reader_{}'.format(kl)].AddVariable('met_px'	  ,  self.bdt_met_px  ['bdt_met_px_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('met_py'	  ,  self.bdt_met_py  ['bdt_met_py_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('haa_pt'	  ,  self.bdt_haa_pt  ['bdt_haa_pt_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('haa_eta'	  ,  self.bdt_haa_eta ['bdt_haa_eta_{}'.format(kl)]   )
            self.reader['reader_{}'.format(kl)].AddVariable('haa_phi'	  ,  self.bdt_haa_phi ['bdt_haa_phi_{}'.format(kl)]   )
            self.reader['reader_{}'.format(kl)].AddVariable('haa_m'	  ,  self.bdt_haa_m   ['bdt_haa_m_{}'.format(kl)]     )
            self.reader['reader_{}'.format(kl)].AddVariable('hbb_pt'	  ,  self.bdt_hbb_pt  ['bdt_hbb_pt_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('hbb_eta'	  ,  self.bdt_hbb_eta ['bdt_hbb_eta_{}'.format(kl)]   )
            self.reader['reader_{}'.format(kl)].AddVariable('hbb_phi'	  ,  self.bdt_hbb_phi ['bdt_hbb_phi_{}'.format(kl)]   )
            self.reader['reader_{}'.format(kl)].AddVariable('hbb_m'	  ,  self.bdt_hbb_m   ['bdt_hbb_m_{}'.format(kl)]     )
            self.reader['reader_{}'.format(kl)].AddVariable('hh_pt'	  ,  self.bdt_hh_pt   ['bdt_hh_pt_{}'.format(kl)]     )
            self.reader['reader_{}'.format(kl)].AddVariable('hh_eta'	  ,  self.bdt_hh_eta  ['bdt_hh_eta_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('hh_phi'	  ,  self.bdt_hh_phi  ['bdt_hh_phi_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('hh_m'	  ,  self.bdt_hh_m    ['bdt_hh_m_{}'.format(kl)]      )
            self.reader['reader_{}'.format(kl)].AddVariable('njets'	  ,  self.bdt_njets   ['bdt_njets_{}'.format(kl)]     )
            self.reader['reader_{}'.format(kl)].AddVariable('nbjets'	  ,  self.bdt_nbjets  ['bdt_nbjets_{}'.format(kl)]    )
            self.reader['reader_{}'.format(kl)].AddVariable('nljets'	  ,  self.bdt_nljets  ['bdt_nljets_{}'.format(kl)]    )
                                                                                                	    
            self.reader2['reader2_{}'.format(kl)].AddVariable('a1_pt'	  ,  self.bdt2_a1_pt  ['bdt2_a1_pt_{}'.format(kl)]    )
            self.reader2['reader2_{}'.format(kl)].AddVariable('a1_eta'    ,  self.bdt2_a1_eta ['bdt2_a1_eta_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('a1_phi'    ,  self.bdt2_a1_phi ['bdt2_a1_phi_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('a2_pt'	  ,  self.bdt2_a2_pt  ['bdt2_a2_pt_{}'.format(kl)]    )
            self.reader2['reader2_{}'.format(kl)].AddVariable('a2_eta'    ,  self.bdt2_a2_eta ['bdt2_a2_eta_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('a2_phi'    ,  self.bdt2_a2_phi ['bdt2_a2_phi_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('b1_pt'	  ,  self.bdt2_b1_pt  ['bdt2_b1_pt_{}'.format(kl)]    )
            self.reader2['reader2_{}'.format(kl)].AddVariable('b1_eta'    ,  self.bdt2_b1_eta ['bdt2_b1_eta_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('b1_phi'    ,  self.bdt2_b1_phi ['bdt2_b1_phi_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('b2_pt'	  ,  self.bdt2_b2_pt  ['bdt2_b2_pt_{}'.format(kl)]    )
            self.reader2['reader2_{}'.format(kl)].AddVariable('b2_eta'    ,  self.bdt2_b2_eta ['bdt2_b2_eta_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('b2_phi'    ,  self.bdt2_b2_phi ['bdt2_b2_phi_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('met_pt'    ,  self.bdt2_met_pt ['bdt2_met_pt_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('met_phi'   ,  self.bdt2_met_phi['bdt2_met_phi_{}'.format(kl)]  )
            self.reader2['reader2_{}'.format(kl)].AddVariable('met_px'    ,  self.bdt2_met_px ['bdt2_met_px_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('met_py'    ,  self.bdt2_met_py ['bdt2_met_py_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('haa_pt'    ,  self.bdt2_haa_pt ['bdt2_haa_pt_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('haa_eta'   ,  self.bdt2_haa_eta['bdt2_haa_eta_{}'.format(kl)]  )
            self.reader2['reader2_{}'.format(kl)].AddVariable('haa_phi'   ,  self.bdt2_haa_phi['bdt2_haa_phi_{}'.format(kl)]  )
            self.reader2['reader2_{}'.format(kl)].AddVariable('haa_m'	  ,  self.bdt2_haa_m  ['bdt2_haa_m_{}'.format(kl)]    )
            self.reader2['reader2_{}'.format(kl)].AddVariable('hbb_pt'    ,  self.bdt2_hbb_pt ['bdt2_hbb_pt_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('hbb_eta'   ,  self.bdt2_hbb_eta['bdt2_hbb_eta_{}'.format(kl)]  )
            self.reader2['reader2_{}'.format(kl)].AddVariable('hbb_phi'   ,  self.bdt2_hbb_phi['bdt2_hbb_phi_{}'.format(kl)]  )
            self.reader2['reader2_{}'.format(kl)].AddVariable('hbb_m'	  ,  self.bdt2_hbb_m  ['bdt2_hbb_m_{}'.format(kl)]    )
            self.reader2['reader2_{}'.format(kl)].AddVariable('hh_pt'	  ,  self.bdt2_hh_pt  ['bdt2_hh_pt_{}'.format(kl)]    )
            self.reader2['reader2_{}'.format(kl)].AddVariable('hh_eta'    ,  self.bdt2_hh_eta ['bdt2_hh_eta_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('hh_phi'    ,  self.bdt2_hh_phi ['bdt2_hh_phi_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('hh_m'	  ,  self.bdt2_hh_m   ['bdt2_hh_m_{}'.format(kl)]     )
            self.reader2['reader2_{}'.format(kl)].AddVariable('njets'	  ,  self.bdt2_njets  ['bdt2_njets_{}'.format(kl)]    )
            self.reader2['reader2_{}'.format(kl)].AddVariable('nbjets'    ,  self.bdt2_nbjets ['bdt2_nbjets_{}'.format(kl)]   )
            self.reader2['reader2_{}'.format(kl)].AddVariable('nljets'    ,  self.bdt2_nljets ['bdt2_nljets_{}'.format(kl)]   )


            path = "/eos/user/s/selvaggi/Analysis/TMVA/hhbbaa_h_v9_1/lambda{}_5f/weights/BDT_BDT_lambda{}_5f.weights.xml".format(kl,kl)
            print path
	    self.reader['reader_{}'.format(kl)].BookMVA("BDT",path)
            path = "/eos/user/s/selvaggi/Analysis/TMVA/hhbbaa_qcd_v9_1/lambda{}_5f/weights/BDT_BDT_lambda{}_5f.weights.xml".format(kl,kl)
            self.reader2['reader2_{}'.format(kl)].BookMVA("BDT",path)

            self.tree.var('tmva_bdt_singleh_{}'.format(kl), float)
            self.tree.var('tmva_bdt_qcd_{}'.format(kl), float)
        
        '''
        self.reader = ROOT.TMVA.Reader()
        self.bdt_a1_pt     = array.array('f',[0])
        self.bdt_a1_eta    = array.array('f',[0])
        self.bdt_a1_phi    = array.array('f',[0])
        self.bdt_a2_pt     = array.array('f',[0])
        self.bdt_a2_eta    = array.array('f',[0])
        self.bdt_a2_phi    = array.array('f',[0])
        self.bdt_b1_pt     = array.array('f',[0])
        self.bdt_b1_eta    = array.array('f',[0])
        self.bdt_b1_phi    = array.array('f',[0])
        self.bdt_b2_pt     = array.array('f',[0])
        self.bdt_b2_eta    = array.array('f',[0])
        self.bdt_b2_phi    = array.array('f',[0])
        self.bdt_met_pt    = array.array('f',[0])
        self.bdt_met_phi   = array.array('f',[0])
        self.bdt_met_px    = array.array('f',[0])
        self.bdt_met_py    = array.array('f',[0])
        self.bdt_haa_pt    = array.array('f',[0])
        self.bdt_haa_eta   = array.array('f',[0])
        self.bdt_haa_phi   = array.array('f',[0])
        self.bdt_haa_m     = array.array('f',[0])
        self.bdt_hbb_pt    = array.array('f',[0])
        self.bdt_hbb_eta   = array.array('f',[0])
        self.bdt_hbb_phi   = array.array('f',[0])
        self.bdt_hbb_m     = array.array('f',[0])
        self.bdt_hh_pt     = array.array('f',[0])
        self.bdt_hh_eta    = array.array('f',[0])
        self.bdt_hh_phi    = array.array('f',[0])
        self.bdt_hh_m      = array.array('f',[0])
        self.bdt_njets     = array.array('f',[0])
        self.bdt_nbjets    = array.array('f',[0])
        self.bdt_nljets    = array.array('f',[0])
        
        self.reader.AddVariable('a1_pt'      , self.bdt_a1_pt)
        self.reader.AddVariable('a1_eta'     , self.bdt_a1_eta)
        self.reader.AddVariable('a1_phi'     , self.bdt_a1_phi)
        self.reader.AddVariable('a2_pt'      , self.bdt_a2_pt)
        self.reader.AddVariable('a2_eta'     , self.bdt_a2_eta)
        self.reader.AddVariable('a2_phi'     , self.bdt_a2_phi)
        self.reader.AddVariable('b1_pt'      , self.bdt_b1_pt)
        self.reader.AddVariable('b1_eta'     , self.bdt_b1_eta)
        self.reader.AddVariable('b1_phi'     , self.bdt_b1_phi)
        self.reader.AddVariable('b2_pt'      , self.bdt_b2_pt)
        self.reader.AddVariable('b2_eta'     , self.bdt_b2_eta)
        self.reader.AddVariable('b2_phi'     , self.bdt_b2_phi)
        self.reader.AddVariable('met_pt'     , self.bdt_met_pt)
        self.reader.AddVariable('met_phi'    , self.bdt_met_phi)
        self.reader.AddVariable('met_px'     , self.bdt_met_px)
        self.reader.AddVariable('met_py'     , self.bdt_met_py)

        self.reader.AddVariable('haa_pt'     , self.bdt_haa_pt)
        self.reader.AddVariable('haa_eta'    , self.bdt_haa_eta)
        self.reader.AddVariable('haa_phi'    , self.bdt_haa_phi)
        self.reader.AddVariable('haa_m'      , self.bdt_haa_m)
        self.reader.AddVariable('hbb_pt'     , self.bdt_hbb_pt)
        self.reader.AddVariable('hbb_eta'    , self.bdt_hbb_eta)
        self.reader.AddVariable('hbb_phi'    , self.bdt_hbb_phi)
        self.reader.AddVariable('hbb_m'      , self.bdt_hbb_m)
        self.reader.AddVariable('hh_pt'      , self.bdt_hh_pt)
        self.reader.AddVariable('hh_eta'     , self.bdt_hh_eta)
        self.reader.AddVariable('hh_phi'     , self.bdt_hh_phi)
        self.reader.AddVariable('hh_m'       , self.bdt_hh_m)

        self.reader.AddVariable('njets'      , self.bdt_njets)
        self.reader.AddVariable('nbjets'     , self.bdt_nbjets)
        self.reader.AddVariable('nljets'     , self.bdt_nljets)

        path = "/eos/user/s/selvaggi/Analysis/TMVA/hhbbaa_qcd_v3/lambda100_5f/weights/BDT_BDT_lambda100_5f.weights.xml"
        self.reader.BookMVA("BDT",path)
        self.tree.var('tmva_bdt_qcd', float)


        self.reader2 = ROOT.TMVA.Reader()
        self.bdt2_a1_pt     = array.array('f',[0])
        self.bdt2_a1_eta    = array.array('f',[0])
        self.bdt2_a1_phi    = array.array('f',[0])
        self.bdt2_a2_pt    = array.array('f',[0])
        self.bdt2_a2_eta    = array.array('f',[0])
        self.bdt2_a2_phi    = array.array('f',[0])
        self.bdt2_b1_pt    = array.array('f',[0])
        self.bdt2_b1_eta    = array.array('f',[0])
        self.bdt2_b1_phi    = array.array('f',[0])
        self.bdt2_b2_pt    = array.array('f',[0])
        self.bdt2_b2_eta    = array.array('f',[0])
        self.bdt2_b2_phi    = array.array('f',[0])
        self.bdt2_met_pt    = array.array('f',[0])
        self.bdt2_met_phi    = array.array('f',[0])
        self.bdt2_met_px    = array.array('f',[0])
        self.bdt2_met_py    = array.array('f',[0])
        self.bdt2_haa_pt    = array.array('f',[0])
        self.bdt2_haa_eta    = array.array('f',[0])
        self.bdt2_haa_phi    = array.array('f',[0])
        self.bdt2_haa_m    = array.array('f',[0])
        self.bdt2_hbb_pt    = array.array('f',[0])
        self.bdt2_hbb_eta    = array.array('f',[0])
        self.bdt2_hbb_phi    = array.array('f',[0])
        self.bdt2_hbb_m    = array.array('f',[0])
        self.bdt2_hh_pt    = array.array('f',[0])
        self.bdt2_hh_eta    = array.array('f',[0])
        self.bdt2_hh_phi    = array.array('f',[0])
        self.bdt2_hh_m    = array.array('f',[0])
        self.bdt2_njets     = array.array('f',[0])
        self.bdt2_nbjets    = array.array('f',[0])
        self.bdt2_nljets    = array.array('f',[0])
        
        self.reader2.AddVariable('a1_pt'     , self.bdt2_a1_pt)
        self.reader2.AddVariable('a1_eta'    , self.bdt2_a1_eta)
        self.reader2.AddVariable('a1_phi'    , self.bdt2_a1_phi)
        self.reader2.AddVariable('a2_pt'     , self.bdt2_a2_pt)
        self.reader2.AddVariable('a2_eta'    , self.bdt2_a2_eta)
        self.reader2.AddVariable('a2_phi'    , self.bdt2_a2_phi)
        self.reader2.AddVariable('b1_pt'      , self.bdt2_b1_pt)
        self.reader2.AddVariable('b1_eta'     , self.bdt2_b1_eta)
        self.reader2.AddVariable('b1_phi'     , self.bdt2_b1_phi)
        self.reader2.AddVariable('b2_pt'      , self.bdt2_b2_pt)
        self.reader2.AddVariable('b2_eta'     , self.bdt2_b2_eta)
        self.reader2.AddVariable('b2_phi'     , self.bdt2_b2_phi)
        self.reader2.AddVariable('met_pt'     , self.bdt2_met_pt)
        self.reader2.AddVariable('met_phi'    , self.bdt2_met_phi)
        self.reader2.AddVariable('met_px'     , self.bdt2_met_px)
        self.reader2.AddVariable('met_py'     , self.bdt2_met_py)
        self.reader2.AddVariable('haa_pt'     , self.bdt2_haa_pt)
        self.reader2.AddVariable('haa_eta'    , self.bdt2_haa_eta)
        self.reader2.AddVariable('haa_phi'    , self.bdt2_haa_phi)
        self.reader2.AddVariable('haa_m'      , self.bdt2_haa_m)
        self.reader2.AddVariable('hbb_pt'     , self.bdt2_hbb_pt)
        self.reader2.AddVariable('hbb_eta'    , self.bdt2_hbb_eta)
        self.reader2.AddVariable('hbb_phi'    , self.bdt2_hbb_phi)
        self.reader2.AddVariable('hbb_m'      , self.bdt2_hbb_m)
        self.reader2.AddVariable('hh_pt'      , self.bdt2_hh_pt)
        self.reader2.AddVariable('hh_eta'     , self.bdt2_hh_eta)
        self.reader2.AddVariable('hh_phi'     , self.bdt2_hh_phi)
        self.reader2.AddVariable('hh_m'       , self.bdt2_hh_m)
        self.reader2.AddVariable('njets'      , self.bdt2_njets)
        self.reader2.AddVariable('nbjets'     , self.bdt2_nbjets)
        self.reader2.AddVariable('nljets'    , self.bdt2_nljets)

        path = "/eos/user/s/selvaggi/Analysis/TMVA/hhbbaa_h_v3/lambda100_5f/weights/BDT_BDT_lambda100_5f.weights.xml"
        self.reader2.BookMVA("BDT",path)
        self.tree.var('tmva_bdt_singleh', float)
        '''

    def process(self, event):
        self.tree.reset()
        haas = getattr(event, self.cfg_ana.haas)
        hbbs  = getattr(event, self.cfg_ana.hbbs)

        haas.sort(key=lambda x: abs(x.m()-125.))
        hbbs.sort(key=lambda x: abs(x.m()-125.))
              
              
        if len(haas) > 0 and len(hbbs) > 0:
            
            self.tree.fill('weight' , event.weight )
            # jet multiplicities
            self.tree.fill('nbjets' , len(event.selected_bs) )
            self.tree.fill('nljets' , len(event.selected_lights) )
            self.tree.fill('njets' , len(event.selected_lights) + len(event.selected_bs))
            self.tree.fill('nlep' , len(event.selected_leptons))
            
            # missing Et
            fillMet(self.tree, 'met', event.met)
            
            # Reco higgses
            photons = []
            photons.append(haas[0].leg1())
            photons.append(haas[0].leg2())
            photons.sort(key=lambda x: x.pt(), reverse=True)
            
            bs = []
            bs.append(hbbs[0].leg1())
            bs.append(hbbs[0].leg2())
            bs.sort(key=lambda x: x.pt(), reverse=True)
            
            hh = Resonance( haas[0], hbbs[0], 25)

            fillParticle(self.tree, 'hh', hh)
            fillParticle(self.tree, 'haa', haas[0])
            fillParticle(self.tree, 'hbb', hbbs[0])
            fillParticle(self.tree, 'a1', photons[0])
            fillParticle(self.tree, 'a2', photons[1])
            fillParticle(self.tree, 'b1', bs[0])
            fillParticle(self.tree, 'b2', bs[1])

            for kl in kl_list:
                # here fill all variables for BDT

                self.bdt_a1_pt    ['bdt_a1_pt_{}'.format(kl)]	  [0] =  photons[0].p4().Pt()
                self.bdt_a1_eta   ['bdt_a1_eta_{}'.format(kl)]    [0] =  photons[0].p4().Eta()
                self.bdt_a1_phi   ['bdt_a1_phi_{}'.format(kl)]    [0] =  photons[0].p4().Phi()
                self.bdt_a2_pt    ['bdt_a2_pt_{}'.format(kl)]	  [0] =  photons[1].p4().Pt()
                self.bdt_a2_eta   ['bdt_a2_eta_{}'.format(kl)]    [0] =  photons[1].p4().Eta()  
                self.bdt_a2_phi   ['bdt_a2_phi_{}'.format(kl)]    [0] =  photons[1].p4().Phi()  
                self.bdt_b1_pt    ['bdt_b1_pt_{}'.format(kl)]	  [0] =  bs[0].p4().Pt()
                self.bdt_b1_eta   ['bdt_b1_eta_{}'.format(kl)]    [0] =  bs[0].p4().Eta()
                self.bdt_b1_phi   ['bdt_b1_phi_{}'.format(kl)]    [0] =  bs[0].p4().Phi()  
                self.bdt_b2_pt    ['bdt_b2_pt_{}'.format(kl)]	  [0] =  bs[1].p4().Pt()
                self.bdt_b2_eta   ['bdt_b2_eta_{}'.format(kl)]    [0] =  bs[1].p4().Eta()
                self.bdt_b2_phi   ['bdt_b2_phi_{}'.format(kl)]    [0] =  bs[1].p4().Phi() 
                self.bdt_met_pt   ['bdt_met_pt_{}'.format(kl)]    [0] =  event.met.p4().Pt()
                self.bdt_met_phi  ['bdt_met_phi_{}'.format(kl)]   [0] =  event.met.p4().Phi()				       
                self.bdt_met_px   ['bdt_met_px_{}'.format(kl)]    [0] =  event.met.p4().Px()
                self.bdt_met_py   ['bdt_met_py_{}'.format(kl)]    [0] =  event.met.p4().Py()
                self.bdt_haa_pt   ['bdt_haa_pt_{}'.format(kl)]    [0] =  haas[0].p4().Pt()
                self.bdt_haa_eta  ['bdt_haa_eta_{}'.format(kl)]   [0] =  haas[0].p4().Eta()				       
                self.bdt_haa_phi  ['bdt_haa_phi_{}'.format(kl)]   [0] =  haas[0].p4().Phi()				       
                self.bdt_haa_m    ['bdt_haa_m_{}'.format(kl)]	  [0] =  haas[0].p4().M()
                self.bdt_hbb_pt   ['bdt_hbb_pt_{}'.format(kl)]    [0] =  hbbs[0].p4().Pt()
                self.bdt_hbb_eta  ['bdt_hbb_eta_{}'.format(kl)]   [0] =  hbbs[0].p4().Eta()				       
                self.bdt_hbb_phi  ['bdt_hbb_phi_{}'.format(kl)]   [0] =  hbbs[0].p4().Phi()				       
                self.bdt_hbb_m    ['bdt_hbb_m_{}'.format(kl)]	  [0] =  hbbs[0].p4().M()
                self.bdt_hh_pt    ['bdt_hh_pt_{}'.format(kl)]	  [0] =  hh.p4().Pt()
                self.bdt_hh_eta   ['bdt_hh_eta_{}'.format(kl)]    [0] =  hh.p4().Eta()
                self.bdt_hh_phi   ['bdt_hh_phi_{}'.format(kl)]    [0] =  hh.p4().Phi() 
                self.bdt_hh_m     ['bdt_hh_m_{}'.format(kl)]	  [0] =  hh.p4().M()
                self.bdt_njets    ['bdt_njets_{}'.format(kl)]	  [0] =  len(event.selected_lights) + len(event.selected_bs)  
                self.bdt_nbjets   ['bdt_nbjets_{}'.format(kl)]    [0] =  len(event.selected_bs) 			      
                self.bdt_nljets   ['bdt_nljets_{}'.format(kl)]    [0] =  len(event.selected_lights)			      

                self.bdt2_a1_pt   ['bdt2_a1_pt_{}'.format(kl)]    [0] =  photons[0].p4().Pt()
                self.bdt2_a1_eta  ['bdt2_a1_eta_{}'.format(kl)]   [0] =  photons[0].p4().Eta()  			       
                self.bdt2_a1_phi  ['bdt2_a1_phi_{}'.format(kl)]   [0] =  photons[0].p4().Phi()  			       
                self.bdt2_a2_pt   ['bdt2_a2_pt_{}'.format(kl)]    [0] =  photons[1].p4().Pt()
                self.bdt2_a2_eta  ['bdt2_a2_eta_{}'.format(kl)]   [0] =  photons[1].p4().Eta()  			       
                self.bdt2_a2_phi  ['bdt2_a2_phi_{}'.format(kl)]   [0] =  photons[1].p4().Phi()  			       
                self.bdt2_b1_pt   ['bdt2_b1_pt_{}'.format(kl)]    [0] =  bs[0].p4().Pt()
                self.bdt2_b1_eta  ['bdt2_b1_eta_{}'.format(kl)]   [0] =  bs[0].p4().Eta()				       
                self.bdt2_b1_phi  ['bdt2_b1_phi_{}'.format(kl)]   [0] =  bs[0].p4().Phi()				       
                self.bdt2_b2_pt   ['bdt2_b2_pt_{}'.format(kl)]    [0] =  bs[1].p4().Pt()
                self.bdt2_b2_eta  ['bdt2_b2_eta_{}'.format(kl)]   [0] =  bs[1].p4().Eta()				       
                self.bdt2_b2_phi  ['bdt2_b2_phi_{}'.format(kl)]   [0] =  bs[1].p4().Phi()				       
                self.bdt2_met_pt  ['bdt2_met_pt_{}'.format(kl)]   [0] =  event.met.p4().Pt()				       
                self.bdt2_met_phi ['bdt2_met_phi_{}'.format(kl)]  [0] =  event.met.p4().Phi()				       
                self.bdt2_met_px  ['bdt2_met_px_{}'.format(kl)]   [0] =  event.met.p4().Px()				       
                self.bdt2_met_py  ['bdt2_met_py_{}'.format(kl)]   [0] =  event.met.p4().Py()				       
                self.bdt2_haa_pt  ['bdt2_haa_pt_{}'.format(kl)]   [0] =  haas[0].p4().Pt()				       
                self.bdt2_haa_eta ['bdt2_haa_eta_{}'.format(kl)]  [0] =  haas[0].p4().Eta()				       
                self.bdt2_haa_phi ['bdt2_haa_phi_{}'.format(kl)]  [0] =  haas[0].p4().Phi()				       
                self.bdt2_haa_m   ['bdt2_haa_m_{}'.format(kl)]    [0] =  haas[0].p4().M()
                self.bdt2_hbb_pt  ['bdt2_hbb_pt_{}'.format(kl)]   [0] =  hbbs[0].p4().Pt()				       
                self.bdt2_hbb_eta ['bdt2_hbb_eta_{}'.format(kl)]  [0] =  hbbs[0].p4().Eta()				       
                self.bdt2_hbb_phi ['bdt2_hbb_phi_{}'.format(kl)]  [0] =  hbbs[0].p4().Phi()				       
                self.bdt2_hbb_m   ['bdt2_hbb_m_{}'.format(kl)]    [0] =  hbbs[0].p4().M()
                self.bdt2_hh_pt   ['bdt2_hh_pt_{}'.format(kl)]    [0] =  hh.p4().Pt()
                self.bdt2_hh_eta  ['bdt2_hh_eta_{}'.format(kl)]   [0] =  hh.p4().Eta()  				       
                self.bdt2_hh_phi  ['bdt2_hh_phi_{}'.format(kl)]   [0] =  hh.p4().Phi()  				       
                self.bdt2_hh_m    ['bdt2_hh_m_{}'.format(kl)]	  [0] =  hh.p4().M()
                self.bdt2_njets   ['bdt2_njets_{}'.format(kl)]    [0] =  len(event.selected_lights) + len(event.selected_bs)  
                self.bdt2_nbjets  ['bdt2_nbjets_{}'.format(kl)]   [0] =  len(event.selected_bs) 			       
                self.bdt2_nljets  ['bdt2_nljets_{}'.format(kl)]   [0] =  len(event.selected_lights)			       

                mva_value2 = self.reader2['reader2_{}'.format(kl)].EvaluateMVA("BDT")
                #print mva_value2
                self.tree.fill( 'tmva_bdt_singleh_{}'.format(kl), mva_value2)

                #print '--------------------------------------------'
                mva_value = self.reader['reader_{}'.format(kl)].EvaluateMVA("BDT")
                #print mva_value
                self.tree.fill( 'tmva_bdt_qcd_{}'.format(kl), mva_value)

                #print kl, mva_value, mva_value2

            self.tree.tree.Fill()

            '''
            self.bdt_a1_pt     [0] =  photons[0].p4().Pt()
            self.bdt_a1_eta    [0] =  photons[0].p4().Eta()
            self.bdt_a1_phi    [0] =  photons[0].p4().Phi()
            self.bdt_a2_pt     [0] =  photons[1].p4().Pt()
            self.bdt_a2_eta    [0] =  photons[1].p4().Eta()  
            self.bdt_a2_phi    [0] =  photons[1].p4().Phi()  
            self.bdt_b1_pt     [0] =  bs[0].p4().Pt()
            self.bdt_b1_eta    [0] =  bs[0].p4().Eta()
            self.bdt_b1_phi    [0] =  bs[0].p4().Phi()  
            self.bdt_b2_pt     [0] =  bs[1].p4().Pt()
            self.bdt_b2_eta    [0] =  bs[1].p4().Eta()
            self.bdt_b2_phi    [0] =  bs[1].p4().Phi() 
            self.bdt_met_pt    [0] =  event.met.p4().Pt()
            self.bdt_met_phi   [0] =  event.met.p4().Phi()
            self.bdt_met_px    [0] =  event.met.p4().Px()
            self.bdt_met_py    [0] =  event.met.p4().Py()
            self.bdt_haa_pt    [0] =  haas[0].p4().Pt()
            self.bdt_haa_eta   [0] =  haas[0].p4().Eta()
            self.bdt_haa_phi   [0] =  haas[0].p4().Phi() 
            self.bdt_haa_m     [0] =  haas[0].p4().M()
            self.bdt_hbb_pt    [0] =  hbbs[0].p4().Pt()
            self.bdt_hbb_eta   [0] =  hbbs[0].p4().Eta()
            self.bdt_hbb_phi   [0] =  hbbs[0].p4().Phi() 
            self.bdt_hbb_m     [0] =  hbbs[0].p4().M()
            self.bdt_hh_pt     [0] =  hh.p4().Pt()
            self.bdt_hh_eta    [0] =  hh.p4().Eta()
            self.bdt_hh_phi    [0] =  hh.p4().Phi() 
            self.bdt_hh_m      [0] =  hh.p4().M()
            self.bdt_njets     [0] =  len(event.selected_lights) + len(event.selected_bs)                                                                                             
            self.bdt_nbjets    [0] =  len(event.selected_bs)                                                                                                                                                      
            self.bdt_nljets    [0] =  len(event.selected_lights)                                                                                                                                            

            self.bdt2_a1_pt    [0] =  photons[0].p4().Pt()
            self.bdt2_a1_eta   [0] =  photons[0].p4().Eta()
            self.bdt2_a1_phi   [0] =  photons[0].p4().Phi()
            self.bdt2_a2_pt    [0] =  photons[1].p4().Pt()
            self.bdt2_a2_eta   [0] =  photons[1].p4().Eta()  
            self.bdt2_a2_phi   [0] =  photons[1].p4().Phi()  
            self.bdt2_b1_pt    [0] =  bs[0].p4().Pt()
            self.bdt2_b1_eta   [0] =  bs[0].p4().Eta()
            self.bdt2_b1_phi   [0] =  bs[0].p4().Phi()  
            self.bdt2_b2_pt    [0] =  bs[1].p4().Pt()
            self.bdt2_b2_eta   [0] =  bs[1].p4().Eta()
            self.bdt2_b2_phi   [0] =  bs[1].p4().Phi() 
            self.bdt2_met_pt   [0] =  event.met.p4().Pt()
            self.bdt2_met_phi  [0] =  event.met.p4().Phi()
            self.bdt2_met_px   [0] =  event.met.p4().Px()
            self.bdt2_met_py   [0] =  event.met.p4().Py()
            self.bdt2_haa_pt   [0] =  haas[0].p4().Pt()
            self.bdt2_haa_eta  [0] =  haas[0].p4().Eta()
            self.bdt2_haa_phi  [0] =  haas[0].p4().Phi() 
            self.bdt2_haa_m    [0] =  haas[0].p4().M()
            self.bdt2_hbb_pt   [0] =  hbbs[0].p4().Pt()
            self.bdt2_hbb_eta  [0] =  hbbs[0].p4().Eta()
            self.bdt2_hbb_phi  [0] =  hbbs[0].p4().Phi() 
            self.bdt2_hbb_m    [0] =  hbbs[0].p4().M()
            self.bdt2_hh_pt    [0] =  hh.p4().Pt()
            self.bdt2_hh_eta   [0] =  hh.p4().Eta()
            self.bdt2_hh_phi   [0] =  hh.p4().Phi() 
            self.bdt2_hh_m     [0] =  hh.p4().M()
            self.bdt2_njets    [0] =  len(event.selected_lights) + len(event.selected_bs)                                                                                             
            self.bdt2_nbjets   [0] =  len(event.selected_bs)                                                                                                                                                      
            self.bdt2_nljets   [0] =  len(event.selected_lights)   
            '''                                                                                                                                        

        
    def write(self, setup):
        self.rootfile.Write()
        self.rootfile.Close()

