ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MS,MDL_MU,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA
     $ ,MDL_MC,MDL_MB,MDL_ME,MDL_MD,MDL_MH,MDL_MMU,MDL_MN1,MDL_MN2
     $ ,MDL_MN3

      COMMON/MASSES/ MDL_MS,MDL_MU,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MC
     $ ,MDL_MB,MDL_ME,MDL_MD,MDL_MH,MDL_MMU,MDL_MN1,MDL_MN2,MDL_MN3


      DOUBLE PRECISION MDL_WN2,MDL_WN3,MDL_WN1,MDL_WZ,MDL_WT,MDL_WW
     $ ,MDL_WH

      COMMON/WIDTHS/ MDL_WN2,MDL_WN3,MDL_WN1,MDL_WZ,MDL_WT,MDL_WW
     $ ,MDL_WH


      DOUBLE COMPLEX GC_58, GC_68, GC_77, GC_84, GC_85, GC_87, GC_172

      COMMON/COUPLINGS/ GC_58, GC_68, GC_77, GC_84, GC_85, GC_87,
     $  GC_172

