ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SM_HeavyN_Dirac_CKM_Masses_LO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_58 = ', GC_58
      WRITE(*,2) 'GC_68 = ', GC_68
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_84 = ', GC_84
      WRITE(*,2) 'GC_85 = ', GC_85
      WRITE(*,2) 'GC_87 = ', GC_87
      WRITE(*,2) 'GC_172 = ', GC_172
