ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SM_HeavyN_CKM_AllMasses_LO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_40 = ', GC_40
      WRITE(*,2) 'GC_44 = ', GC_44
      WRITE(*,2) 'GC_50 = ', GC_50
