"""
this configuration file contains the:
- list of flavors to be considered
- reconstruction sequence stored as two dicts: definition and alias
- the list of variables used in the tagger as well as their range for validation plotting
"""

## number of jets for exclusive clustering
njets = 2

## name of collections in EDM root files
collections = {
    "GenParticles": "Particle",
    "PFParticles": "ReconstructedParticles",
    "PFTracks": "EFlowTrack",
    "PFPhotons": "EFlowPhoton",
    "PFNeutralHadrons": "EFlowNeutralHadron",
    "TrackState": "EFlowTrack_1",
    "TrackerHits": "TrackerHits",
    "CalorimeterHits": "CalorimeterHits",
    "dNdx": "EFlowTrack_2",
    "PathLength": "EFlowTrack_L",
    "Bz": "magFieldBz",
}

#### list of flavors f = g, q, c, s, ...(will look for input file name ccontaining "[Hff]")
flavors = ["g", "q", "s", "c", "b", "tau"]

## define here the branches to be stored in the output root files in addition to the predefined one
## only the name of the var is used here, the metadata is used in stage_plots
variables_pfcand = {
    "pfcand_erel_log": {
        "name": "pfcand_erel_log",
        "title": "log(E_{i}/E_{jet})",
        "bin": 100,
        "xmin": -3,
        "xmax": 0,
        "scale": "log",
    },
    "pfcand_thetarel": {
        "name": "pfcand_thetarel",
        "title": "#theta_{rel}",
        "bin": 100,
        "xmin": 0.0,
        "xmax": 3.0,
        "scale": "lin",
    },
    "pfcand_phirel": {
        "name": "pfcand_phirel",
        "title": "#phi_{rel}",
        "bin": 100,
        "xmin": -3.14,
        "xmax": 3.14,
        "scale": "lin",
    },
    "pfcand_dptdpt": {
        "name": "pfcand_dptdpt",
        "title": "#sigma(#omega)^{2}",
        "bin": 100,
        "xmin": 0.0,
        "xmax": 2e-09,
        "scale": "log",
    },
    "pfcand_detadeta": {
        "name": "pfcand_detadeta",
        "title": "#sigma(tan(#lambda))^{2}",
        "bin": 100,
        "xmin": 0.0,
        "xmax": 0.02,
        "scale": "log",
    },
    "pfcand_dphidphi": {
        "name": "pfcand_dphidphi",
        "title": "#sigma(#phi))^{2}",
        "bin": 100,
        "xmin": 0.0,
        "xmax": 0.0015,
        "scale": "log",
    },
    "pfcand_dxydxy": {
        "name": "pfcand_dxydxy",
        "title": "#sigma(d_{xy}))^{2}",
        "bin": 100,
        "xmin": 0.0,
        "xmax": 0.20,
        "scale": "log",
    },
    "pfcand_dzdz": {
        "name": "pfcand_dzdz",
        "title": "#sigma(d_{z}))^{2}",
        "bin": 100,
        "xmin": 0.0,
        "xmax": 0.50,
        "scale": "log",
    },
    "pfcand_dxydz": {
        "name": "pfcand_dxydz",
        "title": "C(d_{xy},d_{z})",
        "bin": 100,
        "xmin": -10,
        "xmax": 10,
        "scale": "log",
    },
    "pfcand_dphidxy": {
        "name": "pfcand_dphidxy",
        "title": "C(#phi,d_{z})",
        "bin": 100,
        "xmin": -0.1,
        "xmax": 0,
        "scale": "log",
    },
    "pfcand_dlambdadz": {
        "name": "pfcand_dlambdadz",
        "title": "C(tan(#lambda),d_{z})",
        "bin": 100,
        "xmin": -0.5,
        "xmax": 0.1,
        "scale": "log",
    },
    "pfcand_dxyc": {
        "name": "pfcand_dxyc",
        "title": "C(#omega,d_{xy})",
        "bin": 100,
        "xmin": -0.2,
        "xmax": 0.1,
        "scale": "log",
    },
    "pfcand_dxyctgtheta": {
        "name": "pfcand_dxyctgtheta",
        "title": "C(tan(#lambda),d_{xy})",
        "bin": 100,
        "xmin": -0.025,
        "xmax": 0.025,
        "scale": "log",
    },
    "pfcand_phic": {
        "name": "pfcand_phic",
        "title": "C(#omega,#phi)",
        "bin": 100,
        "xmin": -1e-06,
        "xmax": 1e-06,
        "scale": "log",
    },
    "pfcand_phidz": {
        "name": "pfcand_phidz",
        "title": "C(#phi,d_{z})",
        "bin": 100,
        "xmin": -0.05,
        "xmax": 0.05,
        "scale": "log",
    },
    "pfcand_phictgtheta": {
        "name": "pfcand_phictgtheta",
        "title": "C(tan(#lambda),#phi)",
        "bin": 100,
        "xmin": -0.1e-03,
        "xmax": 0.5e03,
        "scale": "log",
    },
    "pfcand_cdz": {
        "name": "pfcand_cdz",
        "title": "C(#omega,d_{z})",
        "bin": 100,
        "xmin": -0.5e-03,
        "xmax": 0.1e-03,
        "scale": "log",
    },
    "pfcand_cctgtheta": {
        "name": "pfcand_cctgtheta",
        "title": "C(#omega, tan(#lambda))",
        "bin": 100,
        "xmin": -1e-06,
        "xmax": 20e-06,
        "scale": "log",
    },
    "pfcand_mtof": {
        "name": "pfcand_mtof",
        "title": "m_{ToF} [GeV]",
        "bin": 100,
        "xmin": 0,
        "xmax": 1.5,
        "scale": "lin",
    },
    "pfcand_dndx": {
        "name": "pfcand_dndx",
        "title": "dN/dx [mm^{-1}]",
        "bin": 100,
        "xmin": 0,
        "xmax": 5,
        "scale": "lin",
    },
    "pfcand_charge": {
        "name": "pfcand_charge",
        "title": "Q",
        "bin": 2,
        "xmin": -0.5,
        "xmax": 1.5,
        "scale": "lin",
    },
    "pfcand_isMu": {
        "name": "pfcand_isMu",
        "title": "is muon",
        "bin": 2,
        "xmin": -0.5,
        "xmax": 1.5,
        "scale": "lin",
    },
    "pfcand_isEl": {
        "name": "pfcand_isEl",
        "title": "is electron",
        "bin": 2,
        "xmin": -0.5,
        "xmax": 1.5,
        "scale": "lin",
    },
    "pfcand_isChargedHad": {
        "name": "pfcand_isChargedHad",
        "title": "is charged hadron",
        "bin": 2,
        "xmin": -0.5,
        "xmax": 1.5,
        "scale": "lin",
    },
    "pfcand_isGamma": {
        "name": "pfcand_isGamma",
        "title": "is photon",
        "bin": 2,
        "xmin": -0.5,
        "xmax": 1.5,
        "scale": "lin",
    },
    "pfcand_isNeutralHad": {
        "name": "pfcand_isNeutralHad",
        "title": "is neutral hadron",
        "bin": 2,
        "xmin": -0.5,
        "xmax": 1.5,
        "scale": "lin",
    },
    "pfcand_type": {
        "name": "pfcand_type",
        "title": "PDG code",
        "bin": 10000,
        "xmin": -5000,
        "xmax": 5000,
        "scale": "lin",
    },
    "pfcand_dxy": {
        "name": "pfcand_dxy",
        "title": "d_{xy} [mm]",
        "bin": 100,
        "xmin": -0.5,
        "xmax": 0.5,
        "scale": "log",
    },
    "pfcand_dz": {
        "name": "pfcand_dz",
        "title": "d_{z} [mm]",
        "bin": 100,
        "xmin": -0.5,
        "xmax": 0.5,
        "scale": "log",
    },
    "pfcand_btagSip2dVal": {
        "name": "pfcand_btagSip2dVal",
        "title": "2D signed IP [mm]",
        "bin": 100,
        "xmin": -0.5,
        "xmax": 5,
        "scale": "log",
    },
    "pfcand_btagSip2dSig": {
        "name": "pfcand_btagSip2dSig",
        "title": "2D signed IP significance",
        "bin": 100,
        "xmin": -10,
        "xmax": 10,
        "scale": "log",
    },
    "pfcand_btagSip3dVal": {
        "name": "pfcand_btagSip3dVal",
        "title": "3D signed IP [mm]",
        "bin": 100,
        "xmin": -0.5,
        "xmax": 5,
        "scale": "log",
    },
    "pfcand_btagSip3dSig": {
        "name": "pfcand_btagSip3dSig",
        "title": "3D signed IP significance",
        "bin": 100,
        "xmin": -8,
        "xmax": 10,
        "scale": "log",
    },
    "pfcand_btagJetDistVal": {
        "name": "pfcand_btagJetDistVal",
        "title": "distance to jet [mm]",
        "bin": 100,
        "xmin": 0,
        "xmax": 5,
        "scale": "log",
    },
    "pfcand_btagJetDistSig": {
        "name": "pfcand_btagJetDistSig",
        "title": "distance to jet (significance)",
        "bin": 100,
        "xmin": 0,
        "xmax": 10,
        "scale": "log",
    },
    ### other pf cand observer variables
    "pfcand_e": {
        "name": "pfcand_e",
        "title": "E [GeV]",
        "bin": 100,
        "xmin": 0,
        "xmax": 100,
        "scale": "log",
    },
    "pfcand_p": {
        "name": "pfcand_p",
        "title": "p [GeV]",
        "bin": 100,
        "xmin": 0,
        "xmax": 100,
        "scale": "log",
    },
    "pfcand_theta": {
        "name": "pfcand_theta",
        "title": "#theta",
        "bin": 100,
        "xmin": 0,
        "xmax": 3.14,
        "scale": "lin",
    },
    "pfcand_phi": {
        "name": "pfcand_phi",
        "title": "#phi",
        "bin": 100,
        "xmin": -3.14,
        "xmax": 3.14,
        "scale": "lin",
    },
}

variables_jet = {
    ### jet based variables
    "jet_p": {
        "name": "jet_p",
        "title": "p_{jet} [GeV]",
        "bin": 100,
        "xmin": 0,
        "xmax": 100.0,
        "scale": "lin",
    },
    "jet_e": {
        "name": "jet_e",
        "title": "E_{jet} [GeV]",
        "bin": 100,
        "xmin": 0,
        "xmax": 100.0,
        "scale": "lin",
    },
    "jet_mass": {
        "name": "jet_mass",
        "title": "m_{jet} [GeV]",
        "bin": 100,
        "xmin": 0,
        "xmax": 25,
        "scale": "lin",
    },
    "jet_phi": {
        "name": "jet_phi",
        "title": "#phi_{jet}",
        "bin": 100,
        "xmin": -3.14,
        "xmax": 3.14,
        "scale": "lin",
    },
    "jet_theta": {
        "name": "jet_theta",
        "title": "#theta_{jet}",
        "bin": 100,
        "xmin": 0,
        "xmax": 3.14,
        "scale": "lin",
    },
    "jet_nconst": {
        "name": "jet_nconst",
        "title": "N_{const}^{jet}",
        "bin": 100,
        "xmin": 0,
        "xmax": 100,
        "scale": "log",
    },
    "jet_nmu": {
        "name": "jet_nmu",
        "title": "N_{#mu}^{jet}",
        "bin": 5,
        "xmin": 0,
        "xmax": 5,
        "scale": "log",
    },
    "jet_nel": {
        "name": "N_{el}^{jet}",
        "title": "",
        "bin": 5,
        "xmin": 0,
        "xmax": 5,
        "scale": "log",
    },
    "jet_nchad": {
        "name": "jet_nchad",
        "title": "N_{ch.had}^{jet}",
        "bin": 50,
        "xmin": 0,
        "xmax": 50,
        "scale": "log",
    },
    "jet_ngamma": {
        "name": "jet_ngamma",
        "title": "N_{#gamma}^{jet}",
        "bin": 50,
        "xmin": 0,
        "xmax": 50,
        "scale": "log",
    },
    "jet_nnhad": {
        "name": "jet_nnhad",
        "title": "N_{neutr. had}^{jet}",
        "bin": 20,
        "xmin": 0,
        "xmax": 20,
        "scale": "log",
    },
}

variables_event = {
    "event_invariant_mass": {
        "name": "event_invariant_mass",
        "title": "m_{jj} [GeV]",
        "bin": 100,
        "xmin": 0,
        "xmax": 200,
        "scale": "lin",
    },
    "event_njet": {
        "name": "event_njet",
        "title": "N_{j} ",
        "bin": 11,
        "xmin": -0.5,
        "xmax": 10,
        "scale": "lin",
    },
}
