.\" Manpage for fccanalysis
.\" Contact FCC-PED-SoftwareAndComputing-Analysis@cern.ch to correct errors or typos.
.TH FCCANALYSIS 1 "17 Jan 2024" "0.9.0" "fccanalysis man page"
.SH NAME
\fBfccanalysis\fR \(en write, build and run your FCC analysis
.SH SYNOPSIS
.B fccanalysis
[\fB\-h\fR]
[\fB\-v\fR | \fB\-vv\fR | \fB\-vvv\fR]
<\fIsub-command\fR>
[<\fIargs\fR>]
.SH DESCRIPTION
.B fccanalysis
is the manager program for the FCC analysis, which can build,
run or submit analysis to the batch\&.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Prints short help message and exits\&.
.TP
.BR \-v ", " \-\-verbose
Makes output verbose. RDataFrame verbosity level is set to
ROOT.Experimental.ELogLevel.kInfo\&.
.TP
.BR \-vv ", " \-\-more\-verbose
Makes output more verbose. RDataFrame verbosity level is set to
ROOT.Experimental.ELogLevel.kDebug\&.
.TP
.BR \-vvv ", " \-\-most\-verbose
Makes output even more verbose. RDataFrame verbosity level is set to
ROOT.Experimental.ELogLevel.kDebug+10 \-\-\- outputs also generated code\&.
.SH SUB-COMMANDS
.TP
.B fccanalysis-init
[Experimental] Generate a RDataFrame based FCC analysis package\&.
.TP
.B fccanalysis-build
Helper to build and install FCCAnalyses framework\&.
.TP
.B fccanalysis-pin
Pin analysis to the currently sourced version of the Key4hep stack\&.
.TP
.B fccanalysis-run
Runs the analysis script provided\&.
.TP
.B fccanalysis-final
Runs the finalization analysis script provided\&.
.TP
.B fccanalysis-plots
Generate plots based on the plots analysis file provided\&.
.TP
.B fccanalysis-test
Helper to run tests of the full FCCAnalyses framework\&.
.SH SEE ALSO
fccanalysis\-run(1), fccanalysis\-script(7)
.SH BUGS
Many
.SH AUTHORS
There are many contributors to the FCCAnalyses framework, but the principal
authors are:
.in +4
Clement Helsens
.br
Valentin Volkl
.br
Gerardo Ganis
.SH FCCANALYSES
Part of the FCCAnalyses framework\&.
.SH LINKS
.PP
.UR https://hep-fcc\&.github\&.io/FCCAnalyses/
FCCAnalyses webpage
.UE
.PP
.UR https://github\&.com/HEP\-FCC/FCCAnalyses/
FCCAnalysises GitHub repository
.UE
.PP
.UR https://fccsw\-forum\&.web\&.cern\&.ch/
FCCSW Forum
.UE
.SH CONTACT
.pp
.MT FCC-PED-SoftwareAndComputing-Analysis@cern.ch
FCC-PED-SoftwareAndComputing-Analysis
.ME
