#! /usr/bin/env bash

set -e

test -d TEST || mkdir TEST
cd TEST

../testpdfs CT10nlo/0
../testpdfs MSTW2008nlo68cl/0
../testpdfs NNPDF30_nlo_as_0118/0

../plotpdfs CT10nlo/0 MSTW2008nlo68cl/0 NNPDF30_nlo_as_0118/0

valgrind ../tests/testgrid && rm -f pdf.dat
