name: Documentation

on:
  push:
    branches:
    - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - name: Start container
      run: |
        docker run -it \
                   --name CI_container \
                   -v ${GITHUB_WORKSPACE}:/Package \
                   -v /cvmfs:/cvmfs:shared \
                   -d ghcr.io/key4hep/key4hep-images/alma9:latest /bin/bash
    - name: Compile Documentation
      run: |
        docker exec CI_container /bin/bash -c 'cd Package
          yum install -y graphviz
          source ./setup.sh
          mkdir -p build
          cd build
          cmake ..
          make doc'
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/doxygen/html
        destination_dir: doc/latest
  man:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mandoc
      run: |
        sudo apt-get install -y mandoc
    - name: Compile HTML pages
      run: |
        .github/scripts/man2html.sh
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./man/html
        destination_dir: man/latest
